import { WORLD_WIDTH, WORLD_HEIGHT, TOWN_HALL_POINT } from "../map/townMap";

/** How long the secret role reveal is shown before the world opens up. */
export const ROLE_REVEAL_MS = 4000;

/** Time between a stranger's kills. */
export const KILL_COOLDOWN_MS = 30_000;

/**
 * Grace period after the world opens before the first kill is allowed, so
 * nobody dies before they've had a chance to move or start a task.
 */
export const KILL_INITIAL_DELAY_MS = 10_000;

/** Free discussion before voting opens. */
export const DISCUSSION_MS = 45_000;

/** How long the ballot stays open, if not everyone votes first. */
export const VOTING_MS = 30_000;

/** How long the results / ejection screen is held before play resumes. */
export const RESULTS_MS = 6_000;

/**
 * How far back the detective's trace looks: a witness must have been seen in
 * the body's room within this many ms of the investigation to count as
 * "recent". Keeps the pool to genuinely recent activity rather than "anyone
 * who was ever in that room".
 */
export const DETECTIVE_TRACE_WINDOW_MS = 45_000;

/** How long the lamplighter's lamp keeps every player visible on the map. */
export const LAMP_DURATION_MS = 3_000;

/**
 * How long a player who drops mid-round keeps their seat. For that window they
 * stay on the map, keep their role, their tasks and their kill cooldown, and
 * still count for every win condition — they are simply marked disconnected.
 * When it expires they are removed as if they had left deliberately.
 *
 * This is the server's grace period; the client retries for the same window,
 * which is why it is shared rather than duplicated on each side. Set with
 * mobile networks in mind — a wifi-to-cellular handoff can plausibly eat
 * 10-20s before a socket recovers, and a still-connected town already plays
 * around a disconnected player rather than blocking on them, so holding the
 * seat a bit longer costs little.
 */
export const RECONNECT_GRACE_MS = 45_000;

/** How long the client waits between reconnection attempts. */
export const RECONNECT_RETRY_MS = 2_000;

export const TIMERS = {
  roleRevealMs: ROLE_REVEAL_MS,
  killCooldownMs: KILL_COOLDOWN_MS,
  killInitialDelayMs: KILL_INITIAL_DELAY_MS,
  discussionMs: DISCUSSION_MS,
  votingMs: VOTING_MS,
  resultsMs: RESULTS_MS,
  reconnectGraceMs: RECONNECT_GRACE_MS,
  reconnectRetryMs: RECONNECT_RETRY_MS,
} as const;

/** The sub-stages a meeting moves through, in order. */
export const MEETING_STAGE = {
  DISCUSSION: "discussion",
  VOTING: "voting",
  RESULTS: "results",
} as const;

export type MeetingStage = (typeof MEETING_STAGE)[keyof typeof MEETING_STAGE];

/**
 * Sentinel target for a "skip vote". Session ids are generated by Colyseus
 * and never collide with this, so it is safe to share the vote field.
 */
export const SKIP_VOTE = "__skip__";

/** Whether a player may change their vote once cast. */
export const VOTES_ARE_CHANGEABLE = false;

/**
 * Whether the results screen reveals who voted for whom. When false only the
 * per-candidate counts are published — the individual ballots stay on the
 * server and are never broadcast at all.
 */
export const VOTES_ARE_PUBLIC = false;

/** Whether a tied vote ejects nobody. When false, a tie is broken at random. */
export const TIE_EJECTS_NOBODY = true;

/**
 * Whether the ejection announcement reveals if the ejected player was a
 * stranger. With this off, no role information is written to public state at
 * all — see `GameRoom.resolveVotes`.
 */
export const CONFIRM_EJECTS = true;

/** Longest chat message the server will accept, in characters. */
export const MAX_CHAT_LENGTH = 200;

/** Minimum gap between one player's chat messages, in ms. */
export const CHAT_COOLDOWN_MS = 400;

/**
 * The two chat channels. "living" is broadcast only to living clients and
 * "dead" only to dead ones — the split is enforced by sending to a filtered
 * client list on the server, never by hiding messages in the UI.
 */
export const CHAT_CHANNEL = {
  LIVING: "living",
  DEAD: "dead",
} as const;

export type ChatChannel = (typeof CHAT_CHANNEL)[keyof typeof CHAT_CHANNEL];

/** One chat line, as delivered to the clients entitled to see it. */
export interface ChatMessage {
  id: string;
  channel: ChatChannel;
  senderName: string;
  text: string;
}

/** How close a stranger must be to a victim, in world units. */
export const KILL_RANGE = 60;

/**
 * The fog. How far a player can see, in world units, decided by the tile
 * they are standing on. Outdoors — the Streets, the alleys, the tunnel —
 * the fog hangs thick and vision is short; under a roof the air is clear
 * and a whole room is visible at once.
 *
 * These numbers are the game's signature knob, and they are enforced on the
 * server: a player beyond this radius (or behind a wall — see
 * `hasLineOfSight`) is not merely undrawn, their position is never put on
 * the wire at all. See the `filterChildren` on `GameState.players`.
 *
 * Both comfortably exceed `KILL_RANGE` and `REPORT_BODY_RANGE`, so nothing
 * can ever be close enough to interact with yet too foggy to see.
 */
export const VISION_RADIUS_INDOOR = 260;
export const VISION_RADIUS_OUTDOOR = 170;

/**
 * Whether the dead can keep completing tasks.
 *
 * This is on by default for a structural reason, not just flavour: the task
 * bar's total is fixed at game start from every townsfolk's list, so if the
 * dead stopped contributing, a single early kill would make the bar
 * mathematically impossible to fill and the town could never win that way.
 */
export const GHOSTS_CAN_DO_TASKS = true;

/**
 * Where the emergency bell lives, and where everyone teleports for a
 * meeting. Sourced from the town map rather than hand-picked — see
 * `TOWN_HALL_POINT`'s own doc for why that specific plaza point.
 */
export const TOWN_HALL = TOWN_HALL_POINT;

/** Radius of the circle players are arranged in around the Town Hall. */
export const MEETING_SPAWN_RADIUS = 80;

/** How close a living player must be to report a body. */
export const REPORT_BODY_RANGE = 60;

/** How close a living player must be to ring the emergency bell. */
export const BELL_RANGE = 60;

/** Emergency meetings (bell rings) each player gets for the whole game. */
export const EMERGENCY_MEETINGS_PER_PLAYER = 1;

/**
 * Whether the bell is unusable while a sabotage is active. No sabotage
 * mechanic exists yet — this exists so a later milestone can flip
 * `GameRoom`'s internal `sabotageActive` flag without touching this file.
 */
export const BELL_LOCKED_DURING_SABOTAGE = true;

/** How long the base Stranger's sabotage darkens the town for. */
export const SABOTAGE_DURATION_MS = 12_000;
/** Time between a Stranger's sabotages. */
export const SABOTAGE_COOLDOWN_MS = 45_000;
/** Vision radius for every player, of every faction, while a sabotage is active. */
export const SABOTAGE_VISION_RADIUS = 70;
/** How long the Saboteur's stronger sabotage darkens the town for. */
export const ADVANCED_SABOTAGE_DURATION_MS = 20_000;
/** Time between a Saboteur's advanced sabotages. */
export const ADVANCED_SABOTAGE_COOLDOWN_MS = 40_000;
/** Time between a Saboteur's door locks. */
export const DOOR_LOCK_COOLDOWN_MS = 20_000;
/** How long a locked room's doors stay locked. */
export const DOOR_LOCK_DURATION_MS = 15_000;
/** Time between a Stranger's tunnel trips. */
export const TUNNEL_COOLDOWN_MS = 25_000;
/** How close to a tunnel endpoint a Stranger must stand to use it. */
export const TUNNEL_USE_RANGE = 40;
/** How far a tunnel's entry/exit sound carries — deliberately wider than sight, since sound isn't blocked by walls the way sight is. */
export const TUNNEL_SOUND_RADIUS = 260;
/** Time between a Shapeshifter's disguises. */
export const SHAPESHIFT_COOLDOWN_MS = 20_000;
/** How long a Shapeshifter's disguise lasts. */
export const SHAPESHIFT_DURATION_MS = 9_000;
/** Time between a Silencer's silences. */
export const SILENCE_COOLDOWN_MS = 30_000;

/** How long the Saboteur's comms sabotage blacks out the task list and room labels for. */
export const COMMS_SABOTAGE_DURATION_MS = 15_000;
/** Time between a Saboteur's comms sabotages. */
export const COMMS_SABOTAGE_COOLDOWN_MS = 35_000;

/**
 * How long the town has to repair a critical sabotage (Lighthouse
 * failure/flooding) before it runs out and hands the Strangers the game —
 * the "clock" threat, a win path that isn't just killing. Both
 * `CRITICAL_REPAIR_POINTS` must be repaired before this elapses.
 */
export const CRITICAL_SABOTAGE_COUNTDOWN_MS = 45_000;
/** Time between a Saboteur's critical sabotages. */
export const CRITICAL_SABOTAGE_COOLDOWN_MS = 60_000;
/** How close a player must stand to a critical repair point to fix it. */
export const REPAIR_RANGE = 60;

/** Authoritative server simulation rate (ticks per second). */
export const TICK_RATE = 20;

/**
 * How many input commands the client samples and sends per second. Each command
 * represents exactly `SIM_DT` seconds of movement, so client prediction and
 * server simulation advance by the same amount regardless of frame or tick
 * timing — this is what makes reconciliation exact.
 */
export const INPUT_RATE = 30;

/** Seconds of movement represented by a single input command. */
export const SIM_DT = 1 / INPUT_RATE;

/** Player movement speed, in world units per second. */
export const PLAYER_SPEED = 220;

/** Player radius in world units (used for rendering and bounds clamping). */
export const PLAYER_RADIUS = 16;

/**
 * The play area's outer bounds, in world units — derived from the town
 * map's tile grid so this can never disagree with what is actually walkable.
 */
export const MAP = { width: WORLD_WIDTH, height: WORLD_HEIGHT } as const;

/**
 * Distinct, visually separable player colours, cycled as players join —
 * see `GameRoom.pickColor`. Shared rather than server-only: the client also
 * derives each player's cosmetic character archetype from this same colour
 * (`characters/assign.ts`), and a color list that could drift between the
 * two sides is exactly how "every archetype is reachable" quietly stops
 * being true without either side's tests noticing.
 */
export const PLAYER_COLORS = [
  "#e6194b",
  "#3cb44b",
  "#4363d8",
  "#f58231",
  "#911eb4",
  "#42d4f4",
  "#f032e6",
  "#bfef45",
  "#fabed4",
  "#469990",
] as const;

/** Minimum number of players required before the host can start the game. */
export const MIN_PLAYERS = 4;

/**
 * Maximum players in one room. This is the *game* rule, enforced in
 * `GameRoom.onAuth` — deliberately one below the room's transport-level
 * `maxClients`. That spare seat is what lets an over-capacity joiner reach
 * `onAuth` and be told the room is full, instead of being turned away by the
 * matchmaker with the same generic error a bad room code produces.
 */
export const MAX_PLAYERS = 15;

/**
 * Why the server refused a join. These are custom `ServerError` codes chosen
 * above Colyseus's own `ErrorCode` range (which tops out at 4217) so the client
 * can tell "no such room" from "that room is full" from "that game has already
 * started" — all three of which the matchmaker would otherwise report
 * identically.
 */
export const JOIN_ERROR = {
  ROOM_FULL: 4400,
  IN_PROGRESS: 4401,
  /** The auth token was missing (with guests disabled), malformed, or expired. */
  AUTH_INVALID: 4402,
  /** The account is banned — see `GameRoom.onAuth` and the auth `AuthProvider`. */
  BANNED: 4403,
  /** A guest tried to CREATE a room; guests may only join existing ones. */
  GUEST_NO_CREATE: 4404,
  /**
   * Refused because of a block relationship with the room's host — see
   * `GameRoom.onAuth`'s host check and the friend system's `Block` model.
   */
  BLOCKED: 4405,
} as const;

export type JoinError = (typeof JOIN_ERROR)[keyof typeof JOIN_ERROR];

/**
 * Room lifecycle phases. Shared between client and server so both sides
 * compare against the same literal instead of duplicating magic strings.
 */
export const PHASE = {
  LOBBY: "lobby",
  ROLE_REVEAL: "role_reveal",
  PLAYING: "playing",
  MEETING: "meeting",
  GAME_OVER: "game_over",
} as const;

export type Phase = (typeof PHASE)[keyof typeof PHASE];

/**
 * Why the game ended, alongside `GameState.winningFaction`. Purely
 * informational — every condition is still just true/false on the server;
 * this only records *which* one fired, for the results screen and for tests.
 */
export const WIN_REASON = {
  TASKS: "tasks",
  STRANGERS_EJECTED: "strangers_ejected",
  /**
   * The last stranger disconnected and never came back. Mechanically identical
   * to `STRANGERS_EJECTED` — the town is simply alone — but worth naming
   * separately so the results screen doesn't credit the town with an ejection
   * that never happened.
   */
  STRANGERS_LEFT: "strangers_left",
  PARITY: "parity",
  /**
   * A critical sabotage (Lighthouse failure/flooding) ran out before both
   * `CRITICAL_REPAIR_POINTS` were fixed — the Strangers' win path that isn't
   * killing.
   */
  CRITICAL_SABOTAGE: "critical_sabotage",
} as const;

export type WinReason = (typeof WIN_REASON)[keyof typeof WIN_REASON];

export const GAME_CONFIG = {
  timers: TIMERS,
  tickRate: TICK_RATE,
  inputRate: INPUT_RATE,
  simDt: SIM_DT,
  playerSpeed: PLAYER_SPEED,
  playerRadius: PLAYER_RADIUS,
  map: MAP,
  minPlayers: MIN_PLAYERS,
  maxPlayers: MAX_PLAYERS,
  killRange: KILL_RANGE,
  visionRadiusIndoor: VISION_RADIUS_INDOOR,
  visionRadiusOutdoor: VISION_RADIUS_OUTDOOR,
  ghostsCanDoTasks: GHOSTS_CAN_DO_TASKS,
  townHall: TOWN_HALL,
  meetingSpawnRadius: MEETING_SPAWN_RADIUS,
  reportBodyRange: REPORT_BODY_RANGE,
  bellRange: BELL_RANGE,
  emergencyMeetingsPerPlayer: EMERGENCY_MEETINGS_PER_PLAYER,
  bellLockedDuringSabotage: BELL_LOCKED_DURING_SABOTAGE,
  votesAreChangeable: VOTES_ARE_CHANGEABLE,
  votesArePublic: VOTES_ARE_PUBLIC,
  tieEjectsNobody: TIE_EJECTS_NOBODY,
  confirmEjects: CONFIRM_EJECTS,
} as const;

/** Broadcast-shaped payload telling a client their own death was confirmed. */
export interface KilledMessage {
  by: string;
}

/**
 * One meeting's vote outcome, as carried on the end-of-game summary. `results`
 * (per-candidate counts) is always present — it is exactly what the meeting's
 * own results screen already showed live, just retained. `ballots` (who voted
 * for whom) is left empty unless `VOTES_ARE_PUBLIC`, the same secrecy rule
 * `GameRoom.resolveVotes` already applies to `VoteTally.voterNames` — a game
 * ending does not retroactively make anonymous ballots public.
 */
export interface GameSummaryVoteRound {
  results: Array<{ targetId: string; targetName: string; count: number }>;
  ballots: Array<{ voterId: string; voterName: string; targetId: string; targetName: string }>;
}

/**
 * Broadcast once, the instant `declareGameOver` runs — the "who did what"
 * breakdown behind the results screen. Everyone still seated gets a row here
 * regardless of account status (unlike the persisted stats this same moment
 * also produces — see `GameRoom.recordGameStats` — this is a live display,
 * not a database write, so a guest's round is just as worth showing them).
 */
export interface GameSummaryMessage {
  players: Array<{
    id: string;
    name: string;
    role: string;
    faction: string;
    survived: boolean;
    tasksCompleted: number;
    tasksTotal: number;
  }>;
  voteRounds: GameSummaryVoteRound[];
}
